### ISSUE TITLE
How do you express a VPR query by reference?

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c-ccg/vp-request-spec#2]
Placeholder for the discussion -
When doing a `QueryByExample` request, how would you pass in the `example` by reference? (As opposed to by value, as is currently in the spec.)

**Comment by dlongley** [comment]
@dmitrizagidulin -- Per our discussion, we should briefly describe two approaches to this problem:

1. Shared directories for queries where query handlers have to know about the directories and do dereferencing
2. Shared directories for queries where query handlers don't have to know about the directories and query submitters just do the dereferencing

Both should achieve the use case of "stored" and "reusable" queries. I'm in favor of the second approach because it's a better separation of concerns, reducing overall complexity to implement a query handler and reducing attack surface.

**Comment by msporny** [comment]
The group discussed this on the 2024-07-30 telecon:

The current VPR specification doesn't have a size limitation and the group doesn't expect to limit the size of queries. Adding the ability to dereference queries adds complexity to the client that the group currently cannot justify. This feature can always be added in the future, but for now, the group does not feel like adding the feature is limiting adoption of the VPR specification. If there are size limitation concerns, in protocols like VC API, you are given a URL in a VPR to an exchange to receive the full query request -- that makes things simpler for clients (because they don't have to worry about size limitations).
